name: Sync Repository Counts

on:
  watch:
    types: started
  schedule:
    - cron: "0 16 */29 * *"

  # support Manual
  workflow_dispatch:

jobs:
  sync:
    if: |
      github.event_name == 'schedule' || 
      (
        github.event.sender.login == github.repository_owner &&
        (github.event_name == 'watch' || github.event_name == 'workflow_dispatch')
      )
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Run sync remote script
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_GITHUB_TOKEN }}
          NODE_ENV: production
          SYNC_LOCAL: ${{ github.event_name == 'watch' && 1 || 0 }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: node ./src/utils/sync.mjs

      - name: Run sync local script
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_GITHUB_TOKEN }}
          SYNC_LOCAL: ${{ github.event_name == 'watch' && 1 || 0 }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SYNC_DEV: 1
        run: node ./src/utils/sync.mjs

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: sync repo counts"
          commit_user_name: Kshao123
          commit_user_email: kshao123@users.noreply.github.com
